# Generated by Django 2.1 on 2019-01-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birthdate',
            field=models.DateTimeField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(max_length=191),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.Candidate'),
        ),
    ]
